# Basic site info
title:              "Résumé of Weixuan XIAO"
title_fr:           "CV de Weixuan XIAO"
title_zh:           "蕭威軒的簡歷"
description:        "Student in the University of Technology of Compiegne"
update_time:        "March 29, 2019"
update_time_fr:     "29 mars, 2019"
update_time_zh:     "03/29/2019"

# Site URL settings
url:                https://inokinoki.github.io # main url
baseurl:            /resume # for gh-pages

# Google Analytics ID
google_analytics_code: 

# Build settings
source:             ./
destination:        ./_site
markdown:           kramdown
highlighter:        rouge
timezone:           Europe/Paris
exclude:            ["README.md", "LICENSE.md", "CHANGELOG.md", "serve.sh"]

# Site configurations
compress_html:
  clippings:        all
  comments:         ["<!-- ", " -->"]
  endings:          all
  ignore:
    envs:           [local]
  blanklines:       false
  profile:          false
  startings:        [html, head, body]

sass:
  sass_dir:         assets/scss
  style:            compressed # expanded
